name: ClusterFuzzLite PR fuzzing

on:
  pull_request:
    paths:
      - .clusterfuzzlite/**
      - .github/workflows/clusterfuzzlite-pr.yml
      - quickwit/**

permissions:
  contents: read

concurrency:
  group: clusterfuzzlite-pr-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fuzz:
    name: Fuzz changed code
    runs-on: ubuntu-latest
    steps:
      - name: Build fuzzers
        uses: google/clusterfuzzlite/actions/build_fuzzers@82652fb49e77bc29c35da1167bb286e93c6bcc05 # v1
        with:
          language: rust
          sanitizer: address

      - name: Run fuzzers
        uses: google/clusterfuzzlite/actions/run_fuzzers@82652fb49e77bc29c35da1167bb286e93c6bcc05 # v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fuzz-seconds: 600
          mode: code-change
          sanitizer: address
