name: ClusterFuzzLite Batch
on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

permissions: {}

jobs:
  batch-fuzzing:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        sanitizer: [address]
    steps:
      - uses: actions/checkout@v4
      - name: Build Fuzzers (${{ matrix.sanitizer }})
        uses: google/clusterfuzzlite/actions/build_fuzzers@v1
        with:
          language: rust
          sanitizer: ${{ matrix.sanitizer }}
      - name: Run Fuzzers (${{ matrix.sanitizer }})
        uses: google/clusterfuzzlite/actions/run_fuzzers@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fuzz-seconds: 3600
          mode: 'batch'
          sanitizer: ${{ matrix.sanitizer }}
