name: "Dependency Review"
on: [pull_request]

permissions:
  contents: read

# Ensures that we cancel running jobs for the same PR / same workflow.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: "Dependency Review"
        uses: actions/dependency-review-action@45529485b5eb76184ced07362d2331fd9d26f03f # v4.8.1
        with:
          # This is an minor vuln on the rsa crate, used for
          # google storage.
          allow-ghsas: GHSA-c38w-74pg-36hr,GHSA-4grx-2x9w-596c
