name: Build and publish nightly packages

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"

permissions:
  contents: read

jobs:
  build-macos-binaries:
    name: Build ${{ matrix.target }}
    runs-on: macos-latest
    permissions:
      contents: write
      actions: write
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-apple-darwin, aarch64-apple-darwin]
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/cargo-build-macos-binary
        with:
          target: ${{ matrix.target }}
          version: nightly
          token: ${{ secrets.GITHUB_TOKEN }}
  build-linux-binaries:
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-unknown-linux-gnu, aarch64-unknown-linux-gnu]
    name: Build ${{ matrix.target }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/cross-build-binary
        with:
          target: ${{ matrix.target }}
          version: nightly
          token: ${{ secrets.GITHUB_TOKEN }}
